### PR TITLE
Python: Add a "make install" command and clarify documentation

### LINKED ISSUE #576: Command "python setup.py install" not work :-(
python setup.py install 
not work. error:
C:\DevTools\Python\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory

### PR DESCRIPTION
**Pull request by nicksay**
Closes #576

### CODE REVIEW

**Comment by anthrotype** [comment]
May I suggest that you also mention here in the Readme that the Brotli python module is also available on the Python Package Index (PyPI), precompiled for all cpython versions and the three major desktop platforms, and the way to install is `pip install brotli`?

**Comment by nicksay** [comment]
Good idea

**Comment by nicksay** [comment]
@anthrotype Updated both `README.md` and `python/README.md` to reference `pip install brotli`

**Comment by anthrotype** [comment]
LGTM thanks

**Pull request merged**
