### PR TITLE
Convert java brotli decoder to c# library

### PR DESCRIPTION
**Pull request by brezza92**
Convert java code to C# code
- use test_data.zip in java folder for test

Dependency
- ICSharpCode.SharpZipLib

### CODE REVIEW

**Comment by brezza92** [comment]
I signed it!

**Comment by eustas** [comment]
Hi.

 Was it ported by hand, or with some tool? It would be nice to have some (semi-)automated way to downstream changes from Java port to C#.

**Comment by brezza92** [comment]
I'm ported it by hand.

**Comment by eustas** [comment]
Managed to transpile Java decoder with sharpen. Will publish it soon.

**Comment by eustas** [comment]
Please take a look at #538.
Going to add integration test a little bit later.

**Comment by brezza92** [comment]
@eustas thank you. I will try soon.

**Pull request closed without merging**
