### PR TITLE
Python: Clean up setup.py file

### PR DESCRIPTION
**Pull request by nicksay**

### CODE REVIEW

**Comment by anthrotype** [comment]
the changes are purely cosmetic, hence to some degree subjective, but if you prefer it like that, I don't mind.

**Comment by nicksay** [comment]
Agreed that these are (mostly) cosmetic changes.  There are 2 minor actual changes here:
- I've updated the package `author` to be "The Brotli Authors"
- I've removed the package `author_email`

Otherwise, I think this formatting makes future changes to the extension configuration a little clearer / more isolated.

Any ideas on why the travis build is failing with `unable to execute 'g++-4.2': No such file or directory`?

It passed on my local branch before the pull request:
https://travis-ci.org/nicksay/brotli/jobs/164731291
But failed here:
https://travis-ci.org/google/brotli/jobs/165268025

**Comment by anthrotype** [comment]
Sounds like a Travis CI bug.
See here: https://github.com/python-pillow/pillow-wheels/issues/45#issuecomment-251448111

the workaround is to set `osx_image: xcode6.4`

**Comment by nicksay** [comment]
Ah, great, thanks.  I've sent #436 to solve that bug for now.

**Comment by nicksay** [comment]
I actually had to go back to the previous default `osx_image: beta-xcode6.1` since `xcode6.4` also had errors.

**Comment by nicksay** [comment]
I've added a [temporary commit](https://github.com/google/brotli/pull/435/commits/c5362081eb4a667e1a02d89efed72704155da828) to verify the build passes.  Once #436 is merged, I'll rebase and remove the commit.

**Comment by nicksay** [comment]
cc @nnorwitz FYI

**Comment by rohitkeshwani07** [comment]
I u r

**Comment by anthrotype** [comment]
another workaround to this Travis CI bug, instead of using the old VM, is to call `rvm get head`, as mention here:
https://github.com/travis-ci/travis-ci/issues/6307#issuecomment-233315824

For example:
https://github.com/schwa/SwiftIO/commit/f9914fabda2ee1509bef5110f2028efc424d828d

**Comment by nicksay** [comment]
I've rebased and removed the temporary commit now that @eustas merged #438.

**Comment by nicksay** [comment]
Great, build is passing now; this PR is ready to go.

**Comment by eustas** [comment]
Hi. Looks nice.

Would you mind to drop a few lines to README.md how to use yapf (append a new 'Development' section)

**Comment by nicksay** [comment]
@eustas Absolutely, I'll revert the `setup.cfg` change and open a new PR for both of those.  Do you want that in the base `README.md` or in `python/README.md`?

**Comment by eustas** [comment]
Hi.

 `python/README.md` sounds better, but then you should mention that formatting of setup.py in root directory is also a good habit =)

**Comment by nicksay** [comment]
It took an hour for Travis to finish, but this PR is again ready to go. 😄

**Pull request merged**
