### PR TITLE
Cross compilation support

### PR DESCRIPTION
**Pull request by stephenkyle-ARM**

### CODE REVIEW

**Comment by stephenkyle-ARM** [comment]
Well that's unusual - the CI actually fails to use the arm-linux-gnueabihf compiler successfully, but then doesn't detect that the job failed? Will need investigation.

**Comment by stephenkyle-ARM** [comment]
I've had to drop the aarch64-linux-gnu builder, because there appears to be a bug with the qemu-aarch64 available on Ubuntu trusty.

@eustas, PTAL?

**Comment by eustas** [comment]
Nice!

Unfortunately, for some reason Appveyor build is unhappy: https://ci.appveyor.com/project/szabadka/brotli/build/1.0.0%231360

**Comment by stephenkyle-ARM** [comment]
Ah, looks like TOOLCHAIN (which I was using to select which toolchain to use when running make) is being set in this case, but not to the correct triplet name, so that build is failing, let me rename it...

**Comment by eustas** [comment]
Thanks.

**Pull request merged**
