### PR TITLE
add execution time in verbose mode

### PR DESCRIPTION
**Pull request by ahorek**
before
```
Compressed [file.xxx]: 3.114 MiB -> 3.007 MiB
```

after
```
Compressed [file.xxx]: 3.114 MiB -> 3.007 MiB in 1.98 sec
```

### CODE REVIEW

**Comment by ahorek** [comment]
@googlebot I fixed it.

**Comment by eustas** [comment]
Thanks for the PR.
Console output would be very slow... So "end time" should be taken right after the last flush (lines 900 and 968).

**Comment by ahorek** [comment]
> 
> 
> Thanks for the PR.
> Console output would be very slow... So "end time" should be taken right after the last flush (lines 900 and 968).

thanks, done

**Comment by eustas** [comment]
Great! Landing.

**Pull request merged**
