### PR TITLE
[WIP] copy nsec of atime/mtime in CopyStat #891

### PR DESCRIPTION
**Pull request by JackJey**
for #891 

copy tv_nsec in stat result to dest file.
switching case for APPLE & GLIBC for compatibility but I don't make sure this coves all case.
if this command need to cover windows, I think it needs more switching but I don't have windows env,
so adding [wip] for here and any comments and helps are welcome.

### CODE REVIEW

**Comment by ahorek** [comment]
good catch, unfortunately, this API seems to have many bugs on various platforms :-( https://github.com/kunpengcompute/gzip/blob/master/lib/utimens.c
there's also a Windows port that emulates the ```utimensat``` function via Windows-API calls, so it's possible but ugly.

**Comment by JackJey** [comment]
@ahorek But if it copy's nsec correctly in some platform (not all platform), it's only a improvement for them and no breaking changes for others. So starting from partial support is reasonable for me.

**Comment by ahorek** [comment]
@JackJey I would propose to
1/ move copy nsec into a separate function
2/ use conditions for known platforms that do support it
3/ and provide a fallback for platforms that don't

I'm ok with the partial support approach, but currently it breaks the build on some platforms that were supported before.

**Comment by eustas** [comment]
Should be fixed by #992

**Pull request closed without merging**
