### PR TITLE
Added compare tool dir for gzip comparison.

### PR DESCRIPTION
**Pull request by jboero**
This is a single script in tools that can be used to profile brotli vs gzip for any file at compression levels 1-9.  It charts compression time and compressed size.

### CODE REVIEW

**Comment by jboero** [comment]
I signed it!

**Comment by jboero** [comment]
I'm the only contributor here.. ??

**Comment by jboero** [comment]
I signed it!

**Comment by thc202** [comment]
The email in the commit is surrounded by square brackets, try remove them.

**Comment by jboero** [comment]
Ah I see - local git config got brackets.  Let me try this again.

**Pull request closed without merging**
