### PR TITLE
appveyor: add Visual Studio builds (based on CMake)

### PR DESCRIPTION
**Pull request by nemequ**
This only goes back to VS 12 (2013) because MSVC didn't support log2 until then.

I think I'm done now, unless you want me to do some of the stuff from #374 (pkg-config, install a library, configure-cmake, etc.).

### CODE REVIEW

**Comment by nemequ** [comment]
I added another commit to this which is unrelated to the PR title.  Apparently some versions of CMake will cache the result of the check for log2, so if it fails without linking to libm it would simply skip the test *with* libm.  Changing the name of the variable for the second test (with libm) works around the issue.

The issue with Python on AppVeyor seems to have been caused by a change in AppVeyor; builds which previously worked don't anymore.  I'll submit a bug report with them and try to figure out what is going on there…

**Comment by anthrotype** [comment]
It looks like it's a bug in the latest setuptools not correctly enquoting library paths with spaces.
Maybe you can temporarily try to download an earlier version of setuptools which was known to be workong.
https://github.com/pypa/setuptools/issues/694

**Comment by nemequ** [comment]
Yes, https://github.com/FeodorFitsner/brotli/blob/master/appveyor.yml#L31 fixes the issue.  I'd just like to figure out if we should bother or just wait for setuptools to tag a new release…

**Comment by anthrotype** [comment]
Let's wait, I guess. They are usually pretty quick.

**Comment by anthrotype** [comment]
hmm.. looks like it's not fixed yet:
https://github.com/pypa/setuptools/issues/694#issuecomment-237873988

I think it's a good idea to pin down a specific version of setuptools, instead of always upgrading to the latest at every appveyor build. We could only update setuptools when needed and when we know does not break anything else.

**Comment by anthrotype** [comment]
The latest setuptools v25.1.6 should fix the issue.
https://pypi.python.org/pypi/setuptools/25.1.6

@nemequ can you try to re-run the Appveyor build?

**Comment by nemequ** [comment]
I can't rebuild the PR without changing the commits; @eustas would need to do that.  However, it works in my repository now (see https://ci.appveyor.com/project/quixdb/brotli/build/1.0.26).

**Comment by eustas** [comment]
Appveyor seems to be happy now. Will merge soon.

**Pull request merged**
