### PR TITLE
Add autotools build

### PR DESCRIPTION
**Pull request by eustas**
Also separate semantic and ABI version.

### CODE REVIEW

**Comment by eustas** [comment]
@robryk, @badger, could you take a look, please.

**Comment by bagder** [comment]
I needed this patch, as otherwise automake complains on the lack of a three files. NEWS, AUTHORS and Changelog.

~~~diff
diff --git a/Makefile.am b/Makefile.am
index 55ba9de..e823159 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,6 +1,6 @@
-AUTOMAKE_OPTIONS = gnu nostdinc subdir-objects
+AUTOMAKE_OPTIONS = foreign nostdinc subdir-objects
 
 ACLOCAL_AMFLAGS = -I m4
 
 LIBBROTLI_VERSION_INFO = -version-info @PACKAGE_VERSION@

**Comment by bagder** [comment]
An additional suggestion: put the headers and source files in a separate file that can be included by both cmake and automake (if you intend to keep maintaining both): I've found that to work really well in the curl project. We put them in [Makefile.inc](https://github.com/curl/curl/blob/master/lib/Makefile.inc) files.

**Comment by eustas** [comment]
Done. Thanks.

**Pull request merged**
