### PR TITLE
Add loongarch64 support

### PR DESCRIPTION
**Pull request by loongson-zn**
define BROTLI_TARGET_64_BITS is 1 on loongarch64 platform

### CODE REVIEW

**Review by eustas — APPROVED** [review]

**Comment by eustas** [comment]
Hi. Thanks for PR.

Is there a way to compile for this arch in github actions?

**Comment by loongson-zn** [comment]
I verified it on my personal computer,  but I believe on [Gentoo](https://www.gentoo.org/downloads/#loong) or other upcoming systems (openEuler and Debian) will be successful. 

```
69/70 Test #69: compatibility/tests/testdata/xyzzy.compressed .................   Passed    0.01 sec
      Start 70: compatibility/tests/testdata/zeros.compressed
70/70 Test #70: compatibility/tests/testdata/zeros.compressed .................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 70

Total Test time (real) =   5.35 sec
[zhangna@localhost build]$ arch
loongarch64

```

**Comment by loongson-zn** [comment]
> Thanks for testing, but I'm more worried that future changes won't break build for this arch...

I don't think this problem will occur, at least I can guarantee that there won't be any problem with the LongArch code. If you still have concerns, I will continue to follow up

**Comment by eustas** [comment]
Landed

**Pull request merged**
