### PR TITLE
add -fPIC to make compatible with shared library

### PR DESCRIPTION
**Pull request by witchu**

### CODE REVIEW

**Comment by eustas** [comment]
Hello.

shared.mk is used to extract common configuration from makefiles.

But currently we have no library targets...

What is the disadvantage of placing "-fPIC" simply to CFLAGS and CXXFLAGS environment variables?

**Comment by witchu** [comment]
I made a lua binding, it must be a .so. It not user friendly to build my binding with
```
CFLAGS=-fPIC CXXFLAGS=-fPIC make
```
instead of just
```
make
```




Now, My makefile call
```
make $(MAKE) -C brotli/enc
make $(MAKE) -C brotli/dec
```
But I think I can embed `brotli/enc/*.o` and `brotli/dec/*.o` into my makefile.


Thanks

**Comment by bagder** [comment]
I put up a separate build project that builds a shared and/or static libbrotli library out of the brotli source code and it should use -fPIC already when necessary: https://github.com/bagder/libbrotli

**Comment by eustas** [comment]
Fixed (in premake5 generated makefiles)

**Pull request closed without merging**
