### PR TITLE
add Python 3.5.0 support in Travis and Appveyor builds 

### PR DESCRIPTION
**Pull request by anthrotype**

### CODE REVIEW

**Comment by anthrotype** [comment]
wait a minute, I need to setup the right SDK for Windows 64-bit Python 3.5.0.

**Comment by anthrotype** [comment]
OK, Appveyor is now working with Python 3.5.
(Travis is super slow today, but it's going to be OK, I already tried on mine).

So with this, we shall have precompiled wheels for Python 3.5.0 for both OSX and Windows.
Many thanks to @ogrisel for his https://github.com/ogrisel/python-appveyor-demo, which made Appveyor setup super easy!

**Comment by anthrotype** [comment]
:+1:

**Comment by ogrisel** [comment]
glad I could help.

**Pull request merged**
