### PR TITLE
Blacklist PGI from using conformant array parameters.

### PR DESCRIPTION
**Pull request by nemequ**
There is a bug in pgcc with conformant array parameters where the
length argument is a pointer which triggers a compiler error
(PGC-S-0094, to be specific).  The issue has been reported to PGI and
is being tracked internally as TPR 23778.  For more information, see

  https://www.pgroup.com/userforum/viewtopic.php?t=5501

### CODE REVIEW

**Comment by nemequ** [comment]
If you're interested, I can also add a test for PGI on Travis (via [nemequ/pgi-travis](https://github.com/nemequ/pgi-travis)).

**Comment by eustas** [comment]
Hi. Thank you for help. Yup, PGI environment would be nice to have.

**Comment by nemequ** [comment]
PR updated w/ a PGI build.

**Comment by eustas** [comment]
Thank you.

**Pull request merged**
