### PR TITLE
Python: Decompressor: Streaming decompression support

### PR DESCRIPTION
**Pull request by ttnbs**
python-brotli has Compressor for streaming compression but nothing for
streaming decompression.
This is a straight-forward copy of the Compressor code into the new
class Decompressor.

### CODE REVIEW

**Comment by ttnbs** [comment]
I signed it!

**Comment by eustas** [comment]
Hello. Thanks for the PR!
Just returned from vacation. Going to review your PR this week.

**Comment by eustas** [comment]
Hi. Sorry for the super-long review. Will get back to you as soon as get results from internal reviewer.

**Comment by nicksay** [comment]
Apologies (again) for the delay here.

The extension implementation looks right to me, but we should have some tests to verify correctness before exposing the Python Decompressor class in the module.  To keep from blocking this any longer, @eustas will add a simple test after landing this PR.

**Pull request merged**
