### PR TITLE
Fix appveyor build

### PR DESCRIPTION
**Pull request by eustas**

### CODE REVIEW

**Comment by anthrotype** [comment]
the problem is `pip wheel` command is trying to create a default "build" directory in the root of the repo, but there's a file called BUILD. You can try to pass the `-b`, or `--build <dir>` option to `pip wheel` command to use a different directory where to build into.

**Comment by eustas** [comment]
Tried to add "-b bin" to "pip wheel", it still fails.

**Comment by anthrotype** [comment]
oh I see that.. hm that's weird. Try adding a `-v` verbose flag maybe.

Or also you can try calling the `bdist_wheel` command directly instead of through pip:
```
python setup.py bdist_wheel -b bin -d dist
```

**Comment by anthrotype** [comment]
I was able to replicate the issue locally on my VM.
It looks like a bug in either `setuptools` or `wheel` or `pip` (or all of them!).
With this command line I was able to make it work:
```
python setup.py build -b bin bdist_wheel -d dist
```

It looks like the bdist_wheel command in turns calls the build command which somehow always defaults to create a `build` directory, despite we pass `-b bin` to bdist_wheel...

**Comment by anthrotype** [comment]
yeah, the setup.cfg trick should also fix it :+1:

**Comment by eustas** [comment]
Going to prepare a separate PR, to remove intermediate commits

**Pull request closed without merging**
