### PR TITLE
Python: Use "build" instead of "build_ext" in scripts

### PR DESCRIPTION
**Pull request by nicksay**
---

_edited Oct 28: see updated commit description and in the thread below_

### CODE REVIEW

**Comment by eustas** [comment]
Hello. What is the difference between "build" and "build_ext"?

**Comment by eustas** [comment]
(ooops, rebase is required)

**Comment by anthrotype** [comment]
build will also compile the pure python modules, besides in turn calling build_ext to compile the extension module. It is the correct command to use, now that brotli is a package with some pure python modules. Previously it was a single extension module.

**Comment by nicksay** [comment]
_updated commit description follows_

---

Previously, the Python package consisted of a single extension
module, so `build_ext` was sufficient.  Now, the package
contains a native module and an extension module, so both
`build_py` and `build_ext` are required.  Instead, run `build`,
which calls both `build_py` and `build_ext` automatically.

**Comment by nicksay** [comment]
Also, I rebased to the latest commit on `master`

**Pull request merged**
