### PR TITLE
Split .pc files (#473)

### PR DESCRIPTION
**Pull request by eustas**
* split brotli common/dec/enc .pc files
* add URL, and use DEPENS_PRIVATE generator params

### CODE REVIEW

**Comment by Earnestly** [comment]
Why was this done?

Everything once configured to use `pkg-config ... brotli` now fails...

**Comment by eustas** [comment]
We are terribly sorry for the inconveniences. It was a difficult decision that hit a lot of fans of brotli. But it has to be done to cover more use cases.
In some use-cases brotli encoder is an unbearable burden. So, we decided to split brotli into `encoder` and `decoder` modules. `common` is a part required by both of them; also, there is an alternative variant of `common` module that does not bring dictionary and allows loading it (for very special use-cases).

**Comment by Earnestly** [comment]
I'm not entirely sure why this would require the removal of `brotli.pc` though.  I can understand why you might want to split it for use cases which don't require linking everything, but why remove the `brotli.pc`?

**Comment by eustas** [comment]
It is an unfortunate consequence: we try to avoid redundancy.

**Comment by Earnestly** [comment]
I see, that's an unfortunate view to hold but at least there is a rational for others who might encounter this issue as systems are updated.

**Pull request merged**
