### PR TITLE
[FixBug] Decompression by JNI failed #880

### PR DESCRIPTION
**Pull request by wlwenming**
https://github.com/google/brotli/issues/880

### CODE REVIEW

**Comment by wlwenming** [comment]
@rojkov Please take a look.

**Comment by rojkov** [comment]
Looks like CI is broken for other PRs too. Please ask the repo owners to have a look.

**Comment by wlwenming** [comment]
> @rojkov Please take a look.
> 
> The Travis CI build failed.How to deal with it?

@szabadka Please take a look.

**Comment by eustas** [comment]
I'll take a look when I get free cycles. Sorry for the delays - very busy these days...

**Comment by wlwenming** [comment]
> I'll take a look when I get free cycles. Sorry for the delays - very busy these days...

remind

**Comment by eustas** [comment]
Travis should be fine now. Please rebase.

**Comment by wlwenming** [comment]
@eustas Why does this commit not merge the branch of master？

**Comment by eustas** [comment]
More correct fix for this is ready. Unfortunately, I was too busy to publish it on GitHub. Will do that next week. Sorry for the delay.

**Pull request closed without merging**
