### PR TITLE
install man pages

### PR DESCRIPTION
**Pull request by kloczek**
cmake modyfication to install man pages.

### CODE REVIEW

**Comment by eustas** [comment]
Hi, Tomasz.

Please sign CLA to unblock landing this PR. Thanks.

**Review by eustas — APPROVED** [review]

**Comment by kloczek** [comment]
image

**Comment by eustas** [comment]
Hi. Thanks for confirmation. Will investigate.

**Review by eustas — APPROVED** [review]

**Comment by kloczek** [comment]
Thank you very much 👍 😄

**Pull request merged**
