### PR TITLE
Also install the brotli headers when building the shared libraries. #326

### PR DESCRIPTION
**Pull request by fred-wang**

### CODE REVIEW

**Comment by fred-wang** [comment]
@eustas Can you please take a look to that one-line change? I think this is the remaining important bit to fix issue #326 . The travis failures seem to happen on BUILD_SYSTEM=python, so that should be unrelated to CMake changes?

**Comment by eustas** [comment]
I think it should be:
```
  if(NOT WIN32)
    install(DIRECTORY ${BROTLI_INCLUDE_DIRS}/brotli DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
  endif()
```

**Comment by fred-wang** [comment]
@eustas OK, that works for me too (let's see later if some Cygwin or MSYS2 maintainers complain...). I updated the pull request.

**Comment by eustas** [comment]
I meant, it should be outside of "is shared libs", because when linking statically, includes required as well =)

**Comment by fred-wang** [comment]
@eustas OK, but at the moment we do not install the libraries at all when building in static mode, so the headers are not going to be used anyway. Maybe we want to remove the whole if(BUILD_SHARED_LIBS) here so that we also install the lib & include in static mode too?

**Comment by eustas** [comment]
Sounds logical.

**Comment by fred-wang** [comment]
@eustas OK, done.

**Comment by eustas** [comment]
One last thing (sorry): any reason not to use paths provided by GNUInstallDirs.
I'm not very experienced in that matter, but it feels like this will make build a bit more portable.

**Comment by eustas** [comment]
And CMake wants `ARCHIVE DESTINATION` as well...

**Comment by fred-wang** [comment]
@eustas updated the install directory, but not sure what you mean with your last comment?
(PS: feel free to take over this work if that's faster, I'm not experienced with all these cmake build configs either...)

**Pull request merged**
