### PR TITLE
Fix link in Readme

### PR DESCRIPTION
**Pull request by mehdi-farsi**
As he said:

```
That's one small step for a man, one giant leap for mankind.
```

### CODE REVIEW

**Comment by mehdi-farsi** [comment]
I signed it!

**Comment by nextPrime** [comment]
How about updating the link to https://tools.ietf.org/html/rfc7932, since this is the final and official version of the spec?

**Comment by mehdi-farsi** [comment]
Great idea

**Comment by nextPrime** [comment]
Thanks! I forgot to mention you also need to update the text above the link from "[...] in the following internet draft" to "[...] in the following RFC document" (or something like that).

**Comment by mehdi-farsi** [comment]
Done !

**Comment by szabadka** [comment]
This was done in #404

**Pull request closed without merging**
